name: Android App Release

on:
  push:
    branches: [ main ]

jobs:
  generate-version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune --depth=10000 
        date +%H%M%S-%m%d%y > version.txt
    - name: Upload version.txt
      uses: actions/upload-artifact@v2
      with:
        name: version-date
        path: version.txt

  build-android:
    name: Build and Create release
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.1'
    - name: Get version.txt
      uses: actions/download-artifact@v2
      with:
        name: version-date
    - name: Read version
      id: version
      uses: juliangruber/read-file-action@v1
      with:
        path: version.txt
    - name: Build Android Release
        uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.3.1'
        run: | flutter pub get
        flutter build apk --release --split-per-abi
        flutter build appbundle
    - name: Build Linux Release
        uses: subosito/flutter-action@v2
          with:
            flutter-version: '3.3.1'
        run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
        flutter build linux
        cp build/linux/x64/release/* build/linux/linux
    - name: Create a Release in GitHub
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab,build/linux/linux"
        token: ${{ secrets.GH_TOKEN }}
        tag: ${{ steps.version.outputs.content }}
        commit: ${{ github.sha }}
